language: node_js
notifications:
  email:
    on_success: never
    on_failure: change
node_js:
  - "6.9.5"
before_script:
  - npm install
  - npm install --only=dev
  - npm install --global mocha
script:
  - mocha tests --timeout 5000